name: pyimage
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12
  - anyio=3.6.2
  - aom=3.5.0
  - app-model=0.1.1
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asciitree=0.3.3
  - asttokens=2.1.0
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - bleach=5.0.1
  - blosc=1.21.1
  - bokeh=3.0.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-blosc2=2.4.3
  - ca-certificates=2022.9.24
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.2.0
  - cachey=0.2.1
  - certifi=2022.9.24
  - cffi=1.15.1
  - cfitsio=4.1.0
  - charls=2.3.4
  - charset-normalizer=2.1.1
  - click=8.1.3
  - cloudpickle=2.2.0
  - colorama=0.4.6
  - commonmark=0.9.1
  - contourpy=1.0.6
  - cryptography=38.0.3
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask=2022.11.0
  - dask-core=2022.11.0
  - dataclasses=0.8
  - dav1d=1.0.0
  - debugpy=1.6.3
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.13
  - distributed=2022.11.0
  - docstring_parser=0.13
  - docutils=0.17.1
  - eigen=3.4.0
  - entrypoints=0.4
  - exceptiongroup=1.0.4
  - executing=1.2.0
  - fasteners=0.17.3
  - flit-core=3.8.0
  - fonttools=4.38.0
  - freetype=2.12.1
  - freetype-py=2.3.0
  - fsspec=2022.11.0
  - future=0.18.2
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.74.1
  - glib-tools=2.74.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - h5py=3.7.0
  - hdf5=1.12.2
  - heapdict=1.0.1
  - hsluv=5.0.2
  - icu=58.2
  - idna=3.4
  - imagecodecs=2022.9.26
  - imageio=2.22.0
  - imagesize=1.4.1
  - importlib-metadata=5.0.0
  - importlib_resources=5.10.0
  - in-n-out=0.1.6
  - iniconfig=1.1.1
  - intel-openmp=2022.1.0
  - ipykernel=6.17.1
  - ipython=8.6.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.2
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jsonschema=4.17.0
  - jupyter_client=7.3.4
  - jupyter_core=5.0.0
  - jupyter_server=1.23.2
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.3
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lcms2=2.14
  - lerc=4.0.0
  - libaec=1.0.6
  - libavif=0.11.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=12.0.1
  - libcurl=7.86.0
  - libdeflate=1.14
  - libffi=3.4.2
  - libglib=2.74.1
  - libiconv=1.17
  - liblapack=3.9.0
  - libogg=1.3.4
  - libpng=1.6.38
  - libprotobuf=3.20.2
  - libsodium=1.0.18
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libvorbis=1.3.7
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - locket=1.0.0
  - lz4=4.0.2
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - magicgui=0.6.0
  - markupsafe=2.1.1
  - matplotlib-base=3.6.2
  - matplotlib-inline=0.1.6
  - mistune=2.0.4
  - mkl=2022.1.0
  - msgpack-python=1.0.4
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - napari-console=0.0.6
  - napari-plugin-engine=0.2.0
  - nbclassic=0.4.8
  - nbclient=0.7.0
  - nbconvert=7.2.5
  - nbconvert-core=7.2.5
  - nbconvert-pandoc=7.2.5
  - nbformat=5.7.0
  - nest-asyncio=1.5.6
  - networkx=2.8.8
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - npe2=0.6.1
  - numcodecs=0.10.2
  - numpydoc=1.5.0
  - opencv=4.6.0
  - openjdk=11.0.15
  - openjpeg=2.5.0
  - openssl=3.0.7
  - packaging=21.3
  - pandas=1.5.1
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.3.0
  - pcre2=10.40
  - pep517=0.13.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pint=0.20.1
  - pip=22.3.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=2.5.2
  - pluggy=1.0.0
  - pooch=1.6.0
  - prometheus_client=0.15.0
  - prompt-toolkit=3.0.32
  - psutil=5.9.4
  - psygnal=0.6.1
  - pthread-stubs=0.4
  - pure_eval=0.2.2
  - pycparser=2.21
  - pydantic=1.10.2
  - pygments=2.13.0
  - pyopengl=3.1.6
  - pyopenssl=22.1.0
  - pyparsing=3.0.9
  - pyqt=5.15.4
  - pyqt5-sip=12.9.0
  - pyrsistent=0.19.2
  - pysocks=1.7.1
  - pytest=7.2.0
  - python=3.10.6
  - python-build=0.9.0
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python_abi=3.10
  - pytomlpp=1.0.11
  - pytz=2022.6
  - pywavelets=1.3.0
  - pywin32=304
  - pywinpty=2.0.9
  - pyyaml=6.0
  - pyzmq=24.0.1
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole-base=5.4.0
  - qtpy=2.3.0
  - qtwebkit=5.212
  - requests=2.28.1
  - rich=12.6.0
  - scikit-image=0.19.3
  - scikit-learn=1.1.3
  - scipy=1.9.3
  - send2trash=1.8.0
  - setuptools=65.5.1
  - shellingham=1.5.0
  - sip=6.5.1
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.3.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.3.2.post1
  - sphinx=4.5.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sqlite=3.40.0
  - stack_data=0.6.1
  - symlink-exe-runtime=1.0
  - tabulate=0.8.10
  - tbb=2021.7.0
  - tblib=1.7.0
  - terminado=0.17.0
  - threadpoolctl=3.1.0
  - tifffile=2022.10.10
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.1
  - tqdm=4.64.1
  - traitlets=5.5.0
  - typer=0.7.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022f
  - ucrt=10.0.22621.0
  - unicodedata2=15.0.0
  - urllib3=1.26.11
  - vc=14.3
  - vs2015_runtime=14.32.31332
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.4.2
  - wheel=0.38.4
  - widgetsnbextension=4.0.3
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - wrapt=1.14.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xyzservices=2022.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - zarr=2.13.3
  - zeromq=4.3.4
  - zfp=1.0.0
  - zict=2.2.0
  - zipp=3.10.0
  - zlib=1.2.13
  - zlib-ng=2.0.6
  - zstd=1.5.2
  - pip:
    - imglyb==2.1.0
    - jgo==1.0.5
    - jpype1==1.4.1
    - labeling==0.1.13
    - lazy-loader==0.3
    - lumicks-pylake==1.3.1
    - napari==0.4.18
    - napari-svg==0.1.10
    - numpy==1.25.2
    - pyimagej==1.4.1
    - scyjava==1.9.1
    - superqt==0.6.1
    - vispy==0.12.2
    - xarray==2023.12.0

